### ISSUE TITLE
Python 3 compatibility?

### ISSUE THREAD

**Issue by KhArtNJava** [ricmoo/pyaes#16]
Hello.

I tried `pyaes`, but it doesn't work on Python 3.3.

My code for Python 3.3 is:

```
import pyaes

# Any mode of operation can be used; for this example CTR
key = "This_key_for_demo_purposes_only!"

# Create the mode of operation to encrypt with
mode = pyaes.AESModeOfOperationCTR(key.encode())

# The input and output files
file_in = open('c:/Temp/7202969_hd.mp4')
file_out = open('c:/Temp/7202969_hd.mp4.crypted', 'wb')

# Encrypt the data as a stream, the file is read in 8kb chunks, be default
pyaes.encrypt_stream(mode, file_in, file_out)

# Close the files
file_in.close()
file_out.close()
```

This code fails:

```
d:\Python33>python.exe cr.py
Traceback (most recent call last):
  File "cr.py", line 55, in <module>
    pyaes.encrypt_stream(mode, file_in, file_out)
  File "d:\Python33\lib\site-packages\pyaes\blockfeeder.py", line 220, in encrypt_stream
    _feed_stream(encrypter, in_stream, out_stream, block_size)
  File "d:\Python33\lib\site-packages\pyaes\blockfeeder.py", line 210, in _feed_stream
    converted = feeder.feed(chunk)
  File "d:\Python33\lib\site-packages\pyaes\blockfeeder.py", line 173, in feed
    self._buffer += to_bufferable(data)
  File "d:\Python33\lib\site-packages\pyaes\util.py", line 42, in to_bufferable
    return bytes(ord(b) for b in binary)
ValueError: bytes must be in range(0, 256)
```

How could it be hot-fixed for Python 3.3?

Thank you!

**Comment by KhArtNJava** [comment]
Solved, need input file needs to be opened in 'rb' mode.
