### ISSUE TITLE
Cannot import pyaes

### ISSUE THREAD

**Issue by gambitov** [ricmoo/pyaes#41]
I'm developing a code with telethon, It runs well for a while, but it crashes later and I cannot load it again because it cannot import pyaes. So, I need to restart my PC to load it again. the error is next:

```
Traceback (most recent call last):
  File "analizador.py", line 9, in <module>
    from telethon.sync import TelegramClient, events
  File "/home/gabriel/.local/lib/python3.7/site-packages/telethon/__init__.py", line 1, in <module>
    from .client.telegramclient import TelegramClient
  File "/home/gabriel/.local/lib/python3.7/site-packages/telethon/client/__init__.py", line 12, in <module>
    from .telegrambaseclient import TelegramBaseClient
  File "/home/gabriel/.local/lib/python3.7/site-packages/telethon/client/telegrambaseclient.py", line 11, in <module>
    from ..crypto import rsa
  File "/home/gabriel/.local/lib/python3.7/site-packages/telethon/crypto/__init__.py", line 6, in <module>
    from .aes import AES
  File "/home/gabriel/.local/lib/python3.7/site-packages/telethon/crypto/aes.py", line 9, in <module>
    import pyaes
  File "/usr/local/lib/python3.7/dist-packages/pyaes/__init__.py", line 51, in <module>
    from .aes import AES, AESModeOfOperationCTR, AESModeOfOperationCBC, AESModeOfOperationCFB, AESModeOfOperationECB, AESModeOfOperationOFB, AESModesOfOperation, Counter
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 857, in get_code
  File "<frozen importlib._bootstrap_external>", line 525, in _compile_bytecode
ValueError: bad marshal data (unknown type code)
```
may you help me?, please

**Comment by Lonami** [comment]
For reference, this is the original issue: https://github.com/LonamiWebs/Telethon/issues/3116#issuecomment-885232825

The failing point is when `pyaes` is imported so I've assumed there's somehow an issue here.
